scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
        - cadvisor:8080
  - job_name: node
    static_configs:
      - targets:
        - 192.168.1.140:9100  
#    metric_relabel_configs:
#      - regex: 'container_label_.*'
#        action: labeldrop
